Repository qri-io/dataset, pull requests merged in 2018-06, with the labels that each got.

#128 feat(dsio): ConvertFormat utility function
  dsio/dsio.go
  dsio/json.go
  dsio/streams.go
Labels: in progress

#129 fix(dsio.ErrEOF): should be replaced with io.EOF
  dsio/dsio.go
  dsio/json.go
  dsio/streams.go
Labels: in progress

#130 test(Copy): tests for various Copy operations, and PagedReader
  dsio/streams.go
  dsio/streams_test.go
Labels: in progress

#132 refactor(dataset): Replace schemaScanMode with TopLevelType.
  dsio/cbor.go
  dsio/dsio.go
  dsio/json.go
  dsio/json_test.go
Labels: in progress

#133 feat(dataset.Body): rename Data fields to Body
  compare.go
  compare_test.go
  dataset.go
  dataset_test.go
  dsfs/data.go
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/testdata/cities/expect.dataset.json
  dsfs/testdata/complete/expect.dataset.json
  dsfs/testdata/craigslist/expect.dataset.json
  testdata/datasets/hours.json
  testdata_test.go
  transform_test.go
Labels: feat, in progress

#134 refactor(Body): rename anything named data to body
  .circleci/config.yml
  dataset.go
  dsfs/body.go
  dsfs/body_test.go
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/testdata/cities/body.csv
  dsfs/testdata/cities_no_commit_title/body.csv
  dsfs/testdata/complete/body.csv
  dsfs/testdata/craigslist/body.json
  dsfs/testdata/invalid/body.csv
  dsfs/testdata/invalid_reference/body.csv
  dsfs/testdata/movies/body.csv
  dsfs/testdata_test.go
  dsio/cbor_test.go
  dsio/entry_buffer_test.go
  dsio/entry_test.go
  dsio/json_test.go
  dsio/testdata/cbor/array/body.cbor
  dsio/testdata/cbor/city/body.cbor
  dsio/testdata/cbor/craigslist/body.cbor
  dsio/testdata/cbor/flourinated_compounds_in_fast_food_packaging/body.cbor
  dsio/testdata/cbor/links_array/body.cbor
  dsio/testdata/cbor/links_object/body.cbor
  dsio/testdata/cbor/movies/body.cbor
  dsio/testdata/cbor/object/body.cbor
  dsio/testdata/cbor/sitemap/body.cbor
  dsio/testdata/cbor/sitemap_object/body.cbor
  dsio/testdata/csv/movies/body.csv
  dsio/testdata/csv/movies_sorted_duration_desc/body.csv
  dsio/testdata/csv/movies_sorted_duration_movie_title/body.csv
  dsio/testdata/csv/movies_sorted_movie_title/body.csv
  dsio/testdata/csv/movies_sorted_movie_title_desc/body.csv
  dsio/testdata/json/array/body.json
  dsio/testdata/json/city/body.json
  dsio/testdata/json/craigslist/body.json
  dsio/testdata/json/links_array/body.json
  dsio/testdata/json/links_object/body.json
  dsio/testdata/json/object/body.json
  dsio/testdata/json/sitemap/body.json
  dsio/testdata/json/sitemap_object/body.json
  dsio/testdata/movies/body.cbor
  dsio/testdata/movies/body.csv
  dsio/testdata/movies/body.json
  dstest/dstest.go
  dstest/dstest_test.go
  dstest/testdata/complete/body.csv
  dsutil/dsutil.go
  validate/data_test.go
  validate/testdata/city/body.json
  validate/testdata/craigslist/body.json
  validate/testdata/flourinated_compounds_in_fast_food_packaging/body.cbor
  validate/testdata/movies/body.csv
Labels: Fix, in progress, refactor
