Repository qri-io/dataset, pull requests merged in 2018-02, with the labels that each got.

#79 feat(Save): multiline or long commit title truncated and prepended to commit message
  dsfs/dataset.go
  dsfs/dataset_test.go
Labels: in progress

#81 feat(timestamp): dsfs.Timestamp now an exported function
  dsfs/dataset.go
  dsfs/dataset_test.go
Labels: enhancement, in progress

#87 feat(SetPath): the SetPath function allows outside packages to change the path
  commit.go
  commit_test.go
  dataset.go
  dataset_test.go
  meta.go
  meta_test.go
  structure.go
  structure_test.go
  transform.go
  transform_test.go
  vis_config.go
  vis_config_test.go
Labels: in progress

#88 fix(dsio,dsfs): fix bugs in entry counts, json reader string error
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/testdata/cities/expect.dataset.json
  dsfs/testdata/complete/expect.dataset.json
  dsfs/testdata/craigslist/data.json
  dsfs/testdata/craigslist/expect.dataset.json
  dsio/json.go
  dsio/json_test.go
  dsio/testdata/craigslist.json
  dstest/dstest.go
Labels: in progress

#89 fix(dsio.JSONReader): fix buffer overflow edge case reading large JSON entries
  dsio/json.go
  dsio/json_test.go
  dsio/testdata/sitemap.json
Labels: Fix, in progress

#90 fix(csv): properly handle solo carriage returns
  detect/detect.go
  detect/detect_test.go
  detect/determineFields.go
  detect/json.go
  detect/testdata/police.csv
  detect/testdata/police.structure.json
  dsio/csv.go
  dsio/csv_test.go
  dsio/dsio_test.go
  dsio/json_test.go
  structure.go
Labels: Fix, in progress
