Repository qri-io/dataset, pull requests merged in 2018-05, with the labels that each got.

#118 refactor(CodingPattern): change Coding to Pod
  .circleci/config.yml
  commit.go
  commit_test.go
  dataset.go
  dataset_test.go
  structure.go
  structure_test.go
  transform.go
  transform_test.go
Labels: in progress

#119 feat(DatasetPod): add convenience fields to DSP
  dataset.go
Labels: feat, in progress

#120 perf(dsfs.CreateDataset): parallelize ds prep with io.MultiWriter
  detect/json.go
  detect/json_test.go
  dsfs/dataset.go
Labels: Fix, in progress, perf

#121 Detect track bytes read
  .circleci/config.yml
  detect/cbor.go
  detect/detect.go
  detect/determineFields.go
  detect/json.go
  detect/json_test.go
  dsfs/dataset.go
  dsio/tracked_reader.go
  dsio/tracked_reader_test.go
  dstest/dstest.go
  dstest/dstest_test.go
  dsutil/dataset_yaml.go
  dsutil/dataset_yaml_test.go
  structure.go
  validate/dataset.go
  validate/dataset_test.go
Labels: in progress

#122 feat(CSVOptions): added LazyQuotes, Separator, VariadicFields options
  data_format_config.go
  data_format_config_test.go
  dsfs/dataset_test.go
  dsfs/transform_test.go
  dsio/csv.go
  dsio/csv_test.go
  structure.go
Labels: feat, in progress

#124 refactor(Transform): rename transform fields, write tf scripts with dsfs
  compare.go
  compare_test.go
  dataset_test.go
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/testdata/complete/expect.dataset.json
  dsfs/testdata/complete/input.dataset.json
  dsfs/testdata/complete/transform.sky
  dsfs/transform_test.go
  dstest/dstest.go
  dstest/dstest_test.go
  dstest/testdata/complete/transform.sky
  dsutil/dataset_yaml.go
  dsutil/dataset_yaml_test.go
  transform.go
  transform_test.go
Labels: in progress, refactor

#126 feat(Meta.Set): add Set method to meta
  meta.go
  meta_test.go
Labels: feat, in progress

#125 fix(meta): IsEmpty function does not check to see if `Meta.License` is nil
  dataset.go
  dataset_test.go
  meta.go
  meta_test.go
  testdata/datasets/airport-codes.json
  testdata/metadata/airport-codes.json
  testdata_test.go
Labels: in progress
