Repository qri-io/dataset, pull requests merged in 2019-03, with the labels that each got.

#178 feat(fill_struct): Meta implements SetKeyVal used by FillStruct
  meta.go
Labels: in progress

#179 fix(loadDatasetRefs): add correct path to dataset
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/package.go
  dsfs/package_test.go
Labels: in progress

#180 refactor(GetBaseHash): makes function to get the base id public
  dsfs/package.go
Labels: in progress

#181 feat(Viz.RenderedFile): at dataset creation, save a rendered `index.html` with the dataset
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/package.go
  dsfs/testdata/all_fields/expect.dataset.json
  dsfs/testdata/all_fields/input.dataset.json
  dsutil/dsutil_test.go
  dsutil/zip.go
  dsutil/zip_test.go
  dsviz/render.go
  structure.go
  testdata/vizs/visconfig1.json
  testdata/zip/exported.zip
  viz.go
  viz_test.go
Labels: in progress

#182 refactor(CreateDataset): add `shouldRender` flag
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/transform_test.go
  dsfs/viz_test.go
  subset/subset_test.go
  viz.go
Labels: dsfs, in progress, refactor

#183 fix(xlsx): update broken excelize API dep
  dsio/xslx.go
Labels: Fix, in progress

#184 fix(xlsx): Fix spelling of source filename
  dsio/xlsx.go
Labels: in progress
