Repository qri-io/dataset, pull requests merged in 2019-01, with the labels that each got.

#165 feat(structure.Depth): add depth parameter to detect tabular data
  compare.go
  compare_test.go
  detect/determineFields.go
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/testdata/all_fields/expect.dataset.json
  dsfs/testdata/cities/expect.dataset.json
  dsfs/testdata/craigslist/expect.dataset.json
  dsio/csv.go
  dsio/csv_test.go
  dsio/replacecr/replace_cr.go
  dsio/replacecr/replace_cr_test.go
  dstest/dstest_test.go
  structure.go
  structure_test.go
  subset/subset_test.go
  testdata/structures/hours.json
  testdata_test.go
Labels: feat, in progress

#166 refactor(CreateDataset): first step toward CreateDataset as a write only (to the store) function
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/testdata/cities_no_commit_title/input.dataset.json
  dsfs/transform_test.go
  dsfs/viz_test.go
  subset/subset_test.go
Labels: in progress

#167 fix(zip): WriteZipArchive accepts format option for dataset file
  .circleci/config.yml
  dsutil/zip.go
  dsutil/zip_test.go
Labels: in progress

#168 refactor: change path representations to string values
  commit.go
  commit_test.go
  compare_test.go
  data_format_config_test.go
  dataset.go
  dataset_test.go
  dsfs/body.go
  dsfs/commit_msg.go
  dsfs/commit_msg_test.go
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/meta.go
  dsfs/package.go
  dsfs/package_test.go
  dsfs/structure.go
  dsfs/testdata_test.go
  dsfs/transform.go
  dsfs/transform_test.go
  dsfs/viz.go
  dsfs/viz_test.go
  dsio/entry.go
  dsutil/dsutil_test.go
  dsutil/zip.go
  meta.go
  meta_test.go
  structure.go
  structure_test.go
  subset/subset.go
  subset/subset_test.go
  transform.go
  transform_test.go
  viz.go
  viz_test.go
Labels: in progress, refactor
