Repository qri-io/dataset, pull requests merged in 2019-10, with the labels that each got.

#208 fix(detect): Iterate type counts in a deterministic manner
  detect/determineFields.go
Labels: Fix

#209 fix(NewJSONPrettyWriter): now writer correctly writes object values when indenting
  dsio/json.go
  dsio/json_test.go
  go.mod
  go.sum
Labels: Fix

#211 fix(dsfs.getDepth): fix algorithm & add tests
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/testdata/craigslist/expect.dataset.json
Labels: Fix

#206 refactor(qfs): updates for changes to qfs
  dsfs/commit_msg.go
  dsfs/commit_msg_test.go
  dsfs/dataset_test.go
  dsfs/meta.go
  dsfs/meta_test.go
  dsfs/structure.go
  dsfs/structure_test.go
  dsfs/transform.go
  dsfs/transform_test.go
  dsfs/viz.go
  dsfs/viz_test.go
  dsutil/zip.go
  dsutil/zip_test.go
  go.mod
  go.sum
Labels: refactor

#215 refactor(dsfs): Move dsfs out of this repository and into qri
  dsfs/body.go
  dsfs/body_test.go
  dsfs/commit_msg.go
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/doc.go
  dsfs/file.go
  dsfs/meta.go
  dsfs/package.go
  dsfs/package_test.go
  dsfs/readme.go
  dsfs/structure.go
  dsfs/testdata/all_fields/body.csv
  dsfs/testdata/all_fields/expect.dataset.json
  dsfs/testdata/all_fields/input.dataset.json
  dsfs/testdata/all_fields/template.html
  dsfs/testdata/all_fields/transform.star
  dsfs/testdata/cities/body.csv
  dsfs/testdata/cities/expect.dataset.json
  dsfs/testdata/cities/input.dataset.json
  dsfs/testdata/cities_no_commit_title/body.csv
  dsfs/testdata/cities_no_commit_title/input.dataset.json
  dsfs/testdata/craigslist/body.json
  dsfs/testdata/craigslist/expect.dataset.json
  dsfs/testdata/craigslist/input.dataset.json
  dsfs/testdata/invalid/body.csv
  dsfs/testdata/invalid/input.dataset.json
  dsfs/testdata/invalid_reference/body.csv
  dsfs/testdata/invalid_reference/input.dataset.json
  dsfs/testdata/movies/body.csv
  dsfs/testdata/movies/input.dataset.json
  dsfs/testdata/strict_fail/body.csv
  dsfs/testdata/strict_fail/input.dataset.json
  dsfs/testdata_test.go
  dsfs/transform.go
  dsfs/transform_test.go
  dsfs/viz.go
  dsutil/dataset_yaml.go
  dsutil/dataset_yaml_test.go
  dsutil/dsutil.go
  dsutil/dsutil_test.go
  dsutil/http.go
  dsutil/http_test.go
  dsutil/testdata/dataset.yml
  dsutil/zip.go
  dsutil/zip_test.go
  subset/subset.go
  subset/subset_test.go
  subset/testdata/movies/body.csv
  subset/testdata/movies/input.dataset.json
Labels: dsfs, refactor

#217 chore(mod): update to use go-libp2p-core
  dstest/priv_key.go
  go.mod
  go.sum
Labels: chore
