Repository qri-io/dataset, pull requests merged in 2019-02, with the labels that each got.

#170 feat(xlsx): initial support for xlsx data format, identity dsio
  .circleci/config.yml
  data_format.go
  data_format_config.go
  data_format_config_test.go
  data_format_test.go
  detect/detect.go
  detect/detect_test.go
  detect/determineFields.go
  detect/xlsx.go
  dsfs/dataset.go
  dsio/cbor.go
  dsio/csv.go
  dsio/dsio.go
  dsio/entry_buffer.go
  dsio/identity.go
  dsio/json.go
  dsio/streams.go
  dsio/testdata/xlsx/obj_cell/body.xlsx
  dsio/testdata/xlsx/simple/body.xlsx
  dsio/xlsx_test.go
  dsio/xslx.go
  dsutil/http.go
  generate/generate.go
Labels: Fix, dsio, feat, in progress

#173 fix(dataset): Dataset BodyFile uses BodyPath. Fixes http drag-n-drop.
  dataset.go
Labels: in progress

#174 fix(save): Fix deadlock when saving invalid file
  dsfs/dataset.go
Labels: in progress

#175 feat(dsfs.CreateDataset): add force flag to force an update without changes
  dsfs/dataset.go
  dsfs/dataset_test.go
  dsfs/transform_test.go
  dsfs/viz_test.go
  subset/subset_test.go
Labels: feat, in progress

#176 fix(dsfs.CreateDataset): remove 'no meaninful changes' check
  dsfs/dataset.go
Labels: Fix, in progress

#177 fix(dataset): Dataset has transient field NumVersions
  dataset.go
  dataset_test.go
Labels: in progress
