Repository qri-io/dataset, pull requests merged in 2020-11, with the labels that each got.

#235 Add Stats Component, dsstats package
  compare.go
  compare_test.go
  dataset.go
  dataset_test.go
  dsstats/histosketch/histosektch_test.go
  dsstats/histosketch/histosketch.go
  dsstats/stats.go
  dsstats/stats_test.go
  go.mod
  go.sum
  kind.go
  stats.go
  stats_test.go
Labels: feat

#236 refactor(dsstats): adjust Accumlator to be a Writer
  dsstats/stats.go
  dsstats/stats_test.go
Labels: refactor, stats

#238 expand dstest package to compare datasets, work with golden files
  commit_test.go
  compare.go
  compare_test.go
  dataset.go
  dataset_test.go
  detect/detect_test.go
  detect/json_test.go
  dsio/csv_test.go
  dsio/entry_buffer_test.go
  dsio/xlsx_test.go
  dstest/compare.go
  dstest/golden.go
  go.sum
  meta.go
  meta_test.go
  stats_test.go
  structure.go
  structure_test.go
  testdata/datasets/airport-codes.json
  testdata/metadata/airport-codes.json
  transform_test.go
  validate/dataset.go
  viz_test.go
Labels: Fix, feat, refactor

#239 fix(stats): limiting top-k frequencies to 200
  dsstats/stats.go
  go.sum
Labels: Fix, stats

#240 feat(dstest): add Template function
  dstest/template.go
Labels: feat

#241 fix meta component serialize, add dstest Golden file Compare-And-Update convenience function
  dstest/golden.go
  meta.go
  meta_test.go
Labels: Fix

#242 fix(stats): avoid nil ptr panic
  dsstats/stats.go
Labels: Fix, stats

#243 feat(FeildsEqual,PathMap): add utility methods for comparing datasets
  dataset.go
  dataset_test.go
  readme.go
  readme_test.go
  testdata/readmes/invalidJSON.json
  testdata/readmes/readmeconfig1.json
  testdata/readmes/readmeconfig2.json
  testdata/readmes/readmeconfig3.json
  transform.go
  transform_test.go
  viz.go
  viz_test.go
Labels: feat
