Repository qri-io/dataset, pull requests merged in 2020-05, with the labels that each got.

#224 feat(dsgen): overhaul generate package, add dsgen command for generating datasets
  generate/data.go
  generate/dataset.go
  generate/datatypes.go
  generate/dsgen/main.go
  generate/fields.go
  generate/generate.go
  generate/generate_test.go
  generate/structure.go
  generate/tabular.go
  generate/tabular_test.go
  generate/value.go
  use_generate/main.go
Labels: feat

#225 perf(csv): increase read buffer size for csv reader
  dsio/csv.go
  dsio/replacecr/replace_cr.go
Labels: perf

#226 refactor(jsonschema): updating jsonschema, adding streaming validation
  detect/determineFields_test.go
  go.mod
  go.sum
  readme.go
  structure.go
  transform.go
  validate/data.go
  validate/data_test.go
Labels: refactor

#227 fix(entryreader): json over batch size propperly unmarshals now
  validate/data.go
Labels: Fix
